
import { 
  AppEntity, 
  EntityStatus, 
  EntityType, 
  LoreEntity, 
  AssetEntity, 
  AIEntity, 
  CodeEntity, 
  TaskEntity,
  Project,
  CategoryDefinition
} from './types';

// Helper to generate ISO dates
const now = new Date().toISOString();
const past = (days: number) => new Date(Date.now() - days * 86400000).toISOString();

export const DEFAULT_CATEGORIES: CategoryDefinition[] = [
  { id: 'Character', name: 'Character', name_zh: '角色' },
  { id: 'Location', name: 'Location', name_zh: '地点' },
  { id: 'Timeline', name: 'Timeline', name_zh: '时间线' },
  { id: 'Artifact', name: 'Artifact', name_zh: '物品' },
  { id: 'Faction', name: 'Faction', name_zh: '势力' },
  { id: 'Nation', name: 'Nation', name_zh: '国家' },
  { id: 'Event', name: 'Event', name_zh: '事件' },
  { id: 'Species', name: 'Species', name_zh: '种族' },
  { id: 'Concept', name: 'Concept', name_zh: '概念/设定' },
  { id: 'Cosmology', name: 'Cosmology', name_zh: '世界观' }
];

export const PROJECTS: Project[] = [
  {
    id: 'p1',
    name: 'Chronos: The Gilded Age',
    name_zh: '时空之轮：镀金时代',
    description: 'Steampunk Time-Travel RPG',
    themeColor: 'amber'
  },
  {
    id: 'p2',
    name: 'Ares Mystica',
    name_zh: '战神秘史 (火星玄幻)',
    description: 'Ancient Martian Fantasy & Magic',
    themeColor: 'red'
  },
  {
    id: 'p3',
    name: 'Red Horizon',
    name_zh: '红色地平线 (火星科幻)',
    description: 'Hard Sci-Fi Colonization Sim',
    themeColor: 'blue'
  }
];

export const MOCK_DATA: AppEntity[] = [
  // ==============================================
  // PROJECT 1: CHRONOS (Time Travel)
  // ==============================================
  {
    id: 'lore-001',
    projectId: 'p1',
    title: 'Emperor Valerius "The Clockmaker"',
    title_zh: '瓦勒留斯大帝 “钟表匠”',
    description: 'The antagonist of Act I. Obsessed with reversing the fall of his empire using forbidden chronomancy.',
    description_zh: '第一幕的反派。痴迷于利用禁忌的时间法术逆转帝国的衰落。',
    type: EntityType.LORE,
    status: EntityStatus.APPROVED,
    tags: ['character', 'antagonist', 'boss'],
    category: 'Character',
    content: 'Valerius was born during the Great Eclipse...',
    content_zh: '瓦勒留斯出生于大日食期间，天生对时间流动异常敏感...',
    created_at: past(30),
    updated_at: past(2),
    author_id: 'writer_sarah',
    linked_ids: ['asset-001', 'lore-002', 'ai-002', 'lore-005'] 
  } as LoreEntity,
  {
    id: 'lore-002',
    projectId: 'p1',
    title: 'The Gilded Chrono-Dial',
    title_zh: '镀金时空刻度盘',
    description: 'An ancient artifact capable of localized time reversal. Requires significant energy sources.',
    description_zh: '一件能够局部逆转时间的古老神器。需要巨大的能量源才能启动。',
    type: EntityType.LORE,
    status: EntityStatus.APPROVED,
    tags: ['item', 'key-item', 'magic'],
    category: 'Artifact',
    content: 'Forged in the fires of the Temporal Spire...',
    content_zh: '这件神器是在时间尖塔的永恒之火中锻造而成的...',
    created_at: past(28),
    updated_at: past(10),
    author_id: 'writer_sarah',
    linked_ids: ['lore-001', 'asset-002', 'code-001', 'lore-004']
  } as LoreEntity,
  {
    id: 'lore-003',
    projectId: 'p1',
    title: 'The Temporal Spire',
    title_zh: '时间尖塔',
    description: 'The final dungeon of the game. A tower existing outside of linear time.',
    description_zh: '游戏的最终地下城。一座存在于线性时间之外的高塔。',
    type: EntityType.LORE,
    status: EntityStatus.DRAFT,
    tags: ['location', 'level', 'endgame'],
    category: 'Location',
    content: 'Architecture shifts between Victorian and Cybernetic styles...',
    content_zh: '塔内的建筑风格在维多利亚哥特式和赛博朋克风格之间不断变换...',
    created_at: past(15),
    updated_at: past(1),
    author_id: 'level_designer_mike',
    linked_ids: ['ai-001', 'task-002']
  } as LoreEntity,
  {
    id: 'lore-004',
    projectId: 'p1',
    title: 'The Chrono-Guard',
    title_zh: '时空守卫军',
    description: 'An elite paramilitary group tasked with protecting the timeline from paradoxes.',
    description_zh: '一支精英准军事组织，任务是保护时间线免受悖论的影响。',
    type: EntityType.LORE,
    status: EntityStatus.APPROVED,
    tags: ['faction', 'allies', 'npc'],
    category: 'Faction',
    content: 'Founded by the first Time Traveler, the Guard operates in shadows...',
    content_zh: '由第一位时间旅行者创立，守卫军在阴影中行动，消灭试图改变历史的威胁...',
    created_at: past(60),
    updated_at: past(5),
    author_id: 'writer_sarah',
    linked_ids: ['lore-001', 'lore-002']
  } as LoreEntity,
  {
    id: 'lore-005',
    projectId: 'p1',
    title: 'The Great Eclipse',
    title_zh: '大日食',
    description: 'The cataclysmic event that fractured the timeline and introduced magic.',
    description_zh: '导致时间线断裂并引入魔法的灾难性事件。',
    type: EntityType.LORE,
    status: EntityStatus.APPROVED,
    tags: ['event', 'history', 'cataclysm'],
    category: 'Event',
    content: 'The sky turned purple, and clocks stopped worldwide. Valerius was born on this day.',
    content_zh: '天空变成了紫色，全世界的时钟都停止了转动。瓦勒留斯正是出生在这一天。',
    created_at: past(100),
    updated_at: past(20),
    author_id: 'writer_sarah',
    linked_ids: ['lore-001']
  } as LoreEntity,
  {
    id: 'asset-001',
    projectId: 'p1',
    title: 'Valerius_Base_Mesh_v4.fbx',
    title_zh: '瓦勒留斯_基础模型_v4.fbx',
    description: 'High poly sculpt of Emperor Valerius. Needs retopology.',
    description_zh: '瓦勒留斯大帝的高模雕刻。需要进行拓扑优化。',
    type: EntityType.ASSET,
    status: EntityStatus.REVIEW,
    tags: ['3d', 'character', 'high-poly'],
    fileType: 'Model',
    fileUrl: 'https://example.com/assets/valerius.fbx',
    fileSize: '450MB',
    version: 4,
    created_at: past(10),
    updated_at: past(1),
    author_id: 'artist_jen',
    linked_ids: ['lore-001', 'task-001']
  } as AssetEntity,
  {
    id: 'asset-002',
    projectId: 'p1',
    title: 'Chrono_Dial_Texture_Atlas.png',
    title_zh: '刻度盘_纹理贴图集.png',
    description: 'PBR textures for the Chrono-Dial artifact.',
    description_zh: '时空刻度盘神器的 PBR 材质贴图。',
    type: EntityType.ASSET,
    status: EntityStatus.APPROVED,
    tags: ['texture', 'pbr', 'prop'],
    fileType: 'Texture',
    fileUrl: 'https://picsum.photos/200/200',
    fileSize: '24MB',
    version: 2,
    created_at: past(8),
    updated_at: past(5),
    author_id: 'artist_jen',
    linked_ids: ['lore-002']
  } as AssetEntity,
  {
    id: 'ai-001',
    projectId: 'p1',
    title: 'Spire Architecture Generator',
    title_zh: '尖塔建筑风格生成器',
    description: 'Prompt engineering setup to generate shifting architectural concepts for the Temporal Spire.',
    description_zh: '用于生成时间尖塔变幻莫测的建筑概念图的提示词工程设置。',
    type: EntityType.AI,
    status: EntityStatus.APPROVED,
    tags: ['gen-ai', 'concept-art', 'environment'],
    modelName: 'Gemini-3-Pro-Image-Preview',
    promptTemplate: 'A surreal tower combining Victorian gothic details with futuristic neon circuitry, fog atmosphere, perspective from below looking up...',
    description_zh_prompt: '一座超现实的高塔，结合了维多利亚哥特式细节和未来主义霓虹电路...', 
    parameters: { temperature: 0.8, seed: 42 },
    created_at: past(14),
    updated_at: past(12),
    author_id: 'tech_art_lead',
    linked_ids: ['lore-003', 'asset-003']
  } as AIEntity,
  {
    id: 'ai-002',
    projectId: 'p1',
    title: 'NPC Dialogue: Arrogant Emperor',
    title_zh: 'NPC对话：傲慢的大帝',
    description: 'System instruction for generating dynamic taunts from Valerius during combat.',
    description_zh: '用于在战斗中生成瓦勒留斯动态嘲讽台词的系统指令。',
    type: EntityType.AI,
    status: EntityStatus.REVIEW,
    tags: ['nlp', 'dialogue', 'gameplay'],
    modelName: 'Gemini-2.5-Flash',
    promptTemplate: 'You are Emperor Valerius. You are arrogant, timeless, and see the player as a "fleeting second". Generate a combat taunt based on the player losing health.',
    parameters: { temperature: 1.1, topK: 40 },
    created_at: past(5),
    updated_at: now,
    author_id: 'narrative_designer',
    linked_ids: ['lore-001', 'code-002']
  } as AIEntity,
  {
    id: 'code-001',
    projectId: 'p1',
    title: 'TimeRewindManager.cs',
    title_zh: 'TimeRewindManager.cs (时间倒流管理)',
    description: 'Core logic for recording entity positions and rewinding them on trigger.',
    description_zh: '用于记录实体位置并在触发时倒流的核心逻辑代码。',
    type: EntityType.CODE,
    status: EntityStatus.APPROVED,
    tags: ['c#', 'unity', 'gameplay-mechanic'],
    language: 'C#',
    codeSnippet: `public class TimeRewindManager : MonoBehaviour { ... }`,
    created_at: past(40),
    updated_at: past(2),
    author_id: 'dev_alex',
    linked_ids: ['lore-002']
  } as CodeEntity,
  {
    id: 'code-002',
    projectId: 'p1',
    title: 'LLM_Runtime_Bridge.py',
    title_zh: 'LLM_Runtime_Bridge.py (大模型桥接)',
    description: 'Python service to proxy game state to the LLM for dynamic dialogue.',
    description_zh: '用于将游戏状态代理到 LLM 以生成动态对话的 Python 服务。',
    type: EntityType.CODE,
    status: EntityStatus.DRAFT,
    tags: ['python', 'backend', 'ai-integration'],
    language: 'Python',
    codeSnippet: `def get_boss_taunt(player_hp, boss_phase): ...`,
    created_at: past(4),
    updated_at: now,
    author_id: 'dev_alex',
    linked_ids: ['ai-002']
  } as CodeEntity,
  {
    id: 'task-001',
    projectId: 'p1',
    title: 'Retopologize Valerius Model',
    title_zh: '瓦勒留斯模型拓扑优化',
    description: 'The high poly sculpt is too heavy. Needs to be reduced to <50k tris for engine import.',
    description_zh: '高模雕刻面数过高。需要减少到 50k 三角面以下以便导入引擎。',
    type: EntityType.TASK,
    status: EntityStatus.REVIEW,
    tags: ['art', 'optimization'],
    priority: 'High',
    assignee: 'artist_jen',
    dueDate: new Date(Date.now() + 86400000 * 5).toISOString(),
    isMilestone: false,
    created_at: past(2),
    updated_at: past(1),
    author_id: 'prod_manager',
    linked_ids: ['asset-001']
  } as TaskEntity,
  {
    id: 'task-002',
    projectId: 'p1',
    title: 'Finalize Spire Level Blockout',
    title_zh: '完成尖塔关卡白盒',
    description: 'Need greybox geometry for the Temporal Spire based on the new concept art.',
    description_zh: '根据新的概念图，完成时间尖塔的白盒（Greybox）几何体搭建。',
    type: EntityType.TASK,
    status: EntityStatus.DRAFT,
    tags: ['level-design', 'blockout'],
    priority: 'Medium',
    assignee: 'level_designer_mike',
    dueDate: new Date(Date.now() + 86400000 * 10).toISOString(),
    isMilestone: true,
    created_at: past(5),
    updated_at: past(5),
    author_id: 'prod_manager',
    linked_ids: ['lore-003']
  } as TaskEntity,

  // ==============================================
  // PROJECT 2: ARES MYSTICA (Mars Fantasy)
  // ==============================================
  {
    id: 'mars-lore-001',
    projectId: 'p2',
    title: 'The Crimson High Priest',
    title_zh: '猩红大祭司',
    description: 'Leader of the Dust Walkers. Wields magic drawn from the iron oxide sands.',
    description_zh: '尘行者的领袖。能够从氧化铁沙中汲取魔力。',
    type: EntityType.LORE,
    status: EntityStatus.APPROVED,
    tags: ['character', 'mars', 'magic'],
    category: 'Character',
    content: 'The High Priest claims to hear the breathing of the planet...',
    content_zh: '大祭司声称能听到星球的呼吸声...',
    created_at: past(100),
    updated_at: past(10),
    author_id: 'writer_bob',
    linked_ids: ['mars-asset-001', 'mars-ai-001', 'mars-lore-002']
  } as LoreEntity,
  {
    id: 'mars-lore-002',
    projectId: 'p2',
    title: 'Temple of Red Dust',
    title_zh: '红尘神庙',
    description: 'A massive underground structure dedicated to the Old Martian Gods.',
    description_zh: '一座供奉古老火星神灵的巨大地下建筑。',
    type: EntityType.LORE,
    status: EntityStatus.DRAFT,
    tags: ['location', 'dungeon', 'mystic'],
    category: 'Location',
    content: 'Walls lined with breathing obsidian. The air vibrates with chanting.',
    content_zh: '墙壁上镶嵌着会呼吸的黑曜石。空气中震动着吟唱声。',
    created_at: past(40),
    updated_at: past(2),
    author_id: 'writer_bob',
    linked_ids: ['mars-lore-001', 'mars-asset-001']
  } as LoreEntity,
  {
    id: 'mars-lore-003',
    projectId: 'p2',
    title: 'Iron Oxide Elixir',
    title_zh: '氧化铁灵药',
    description: 'A potion brewed from refined sand, granting temporary stone-skin.',
    description_zh: '由精炼沙土酿制的药水，能赋予使用者暂时的石肤术。',
    type: EntityType.LORE,
    status: EntityStatus.APPROVED,
    tags: ['item', 'consumable'],
    category: 'Artifact',
    content: 'Tastes like rusty metal, but turns flesh as hard as rock.',
    content_zh: '尝起来像生锈的金属，但能让血肉变得坚如磐石。',
    created_at: past(20),
    updated_at: past(5),
    author_id: 'writer_bob',
    linked_ids: ['mars-lore-001']
  } as LoreEntity,
  {
    id: 'mars-lore-004',
    projectId: 'p2',
    title: 'Order of the Dust Walkers',
    title_zh: '尘行者教团',
    description: 'A secretive religious sect that worships the ancient terraforming machines as dormant gods.',
    description_zh: '一个秘密的宗教派别，将古老的大气改造机器视为沉睡的神灵进行崇拜。',
    type: EntityType.LORE,
    status: EntityStatus.APPROVED,
    tags: ['faction', 'zealots', 'enemies'],
    category: 'Faction',
    content: 'They believe awakening the machines will purify the unworthy...',
    content_zh: '他们相信唤醒这些机器将净化那些不配生存的人...',
    created_at: past(80),
    updated_at: past(5),
    author_id: 'writer_bob',
    linked_ids: ['mars-lore-001', 'mars-lore-002']
  } as LoreEntity,
  {
    id: 'mars-asset-001',
    projectId: 'p2',
    title: 'Obsidian_Staff.obj',
    title_zh: '黑曜石法杖.obj',
    description: 'Ceremonial staff for the High Priest. Needs glowing rune effects.',
    description_zh: '大祭司的仪式法杖。需要添加发光的符文特效。',
    type: EntityType.ASSET,
    status: EntityStatus.REVIEW,
    tags: ['3d', 'weapon', 'prop'],
    fileType: 'Model',
    fileUrl: 'https://example.com/assets/staff.obj',
    fileSize: '45MB',
    version: 1,
    created_at: past(20),
    updated_at: past(5),
    author_id: 'artist_ken',
    linked_ids: ['mars-lore-001']
  } as AssetEntity,
  {
    id: 'mars-ai-001',
    projectId: 'p2',
    title: 'Ancient Martian Runes Generator',
    title_zh: '古火星符文生成器',
    description: 'Generates mystical glowing symbols for texture overlays.',
    description_zh: '生成用于纹理叠加的神秘发光符号。',
    type: EntityType.AI,
    status: EntityStatus.APPROVED,
    tags: ['gen-ai', 'texture'],
    modelName: 'Gemini-2.5-Flash-Image',
    promptTemplate: 'Glowing jagged runes carved into red rock, alien language, mystical energy...',
    parameters: { temperature: 0.9, seed: 101 },
    created_at: past(15),
    updated_at: past(2),
    author_id: 'tech_art_lead',
    linked_ids: ['mars-asset-001']
  } as AIEntity,

  // ==============================================
  // PROJECT 3: RED HORIZON (Mars Sci-Fi)
  // ==============================================
  {
    id: 'sci-lore-001',
    projectId: 'p3',
    title: 'Colony Alpha',
    title_zh: '阿尔法殖民地',
    description: 'The first successful permanent settlement in the Valles Marineris.',
    description_zh: '水手号峡谷中第一个成功的永久定居点。',
    type: EntityType.LORE,
    status: EntityStatus.APPROVED,
    tags: ['location', 'base', 'sci-fi'],
    category: 'Location',
    content: 'Established in 2045, Alpha serves as the hub for terraforming...',
    content_zh: '建立于2045年，阿尔法是地球化改造的中心枢纽...',
    created_at: past(200),
    updated_at: past(20),
    author_id: 'writer_dave',
    linked_ids: ['sci-asset-001', 'sci-task-001', 'sci-lore-002']
  } as LoreEntity,
  {
    id: 'sci-lore-002',
    projectId: 'p3',
    title: 'Commander Halloway',
    title_zh: '哈洛威指挥官',
    description: 'The strict but fair leader of Colony Alpha. Retired Earth Force veteran.',
    description_zh: '阿尔法殖民地严厉但公正的领导者。退役的地球军老兵。',
    type: EntityType.LORE,
    status: EntityStatus.APPROVED,
    tags: ['character', 'leader', 'npc'],
    category: 'Character',
    content: 'Halloway lost her arm in the Lunar Wars. She trusts machines more than people.',
    content_zh: '哈洛威在月球战争中失去了手臂。相比人类，她更信任机器。',
    created_at: past(90),
    updated_at: past(15),
    author_id: 'writer_dave',
    linked_ids: ['sci-lore-001', 'sci-task-001']
  } as LoreEntity,
  {
    id: 'sci-lore-003',
    projectId: 'p3',
    title: 'Oxygen Credit Chip',
    title_zh: '氧气信用芯片',
    description: 'Currency used within the colony. Backed by O2 reserves.',
    description_zh: '殖民地内使用的货币。由氧气储备作为担保。',
    type: EntityType.LORE,
    status: EntityStatus.APPROVED,
    tags: ['item', 'currency'],
    category: 'Artifact',
    content: 'A transparent chip containing a pressurized isotope marker.',
    content_zh: '一种包含加压同位素标记的透明芯片。',
    created_at: past(150),
    updated_at: past(10),
    author_id: 'writer_dave',
    linked_ids: ['sci-lore-001']
  } as LoreEntity,
  {
    id: 'sci-lore-004',
    projectId: 'p3',
    title: 'Terraforming Protocol V7',
    title_zh: '大气改造协议 V7',
    description: 'The strict set of rules governing atmospheric processing to ensure stability.',
    description_zh: '管理大气处理以确保稳定性的严格规则集。',
    type: EntityType.LORE,
    status: EntityStatus.APPROVED,
    tags: ['concept', 'law', 'scifi'],
    category: 'Concept',
    content: 'Protocol V7 forbids the release of unprocessed nitrogen...',
    content_zh: 'V7 协议禁止排放未处理的氮气...',
    created_at: past(120),
    updated_at: past(5),
    author_id: 'writer_dave',
    linked_ids: ['sci-lore-001', 'sci-task-001']
  } as LoreEntity,
  {
    id: 'sci-asset-001',
    projectId: 'p3',
    title: 'Terraforming_Unit_v2.fbx',
    title_zh: '大气改造装置_v2.fbx',
    description: 'Industrial heavy machinery asset for the colony exterior.',
    description_zh: '用于殖民地外部的工业重型机械资产。',
    type: EntityType.ASSET,
    status: EntityStatus.APPROVED,
    tags: ['3d', 'hard-surface', 'building'],
    fileType: 'Model',
    fileUrl: 'https://example.com/assets/terraformer.fbx',
    fileSize: '120MB',
    version: 2,
    created_at: past(30),
    updated_at: past(10),
    author_id: 'artist_sarah',
    linked_ids: ['sci-lore-001']
  } as AssetEntity,
  {
    id: 'sci-task-001',
    projectId: 'p3',
    title: 'Fix Oxygen Leak Script',
    title_zh: '修复氧气泄漏脚本',
    description: 'Bug in the life support system logic causing false alarms.',
    description_zh: '生命维持系统逻辑中的 Bug 导致误报。',
    type: EntityType.TASK,
    status: EntityStatus.REVIEW,
    tags: ['bug', 'gameplay'],
    priority: 'Critical',
    assignee: 'dev_mike',
    dueDate: now,
    isMilestone: false,
    created_at: past(2),
    updated_at: now,
    author_id: 'lead_dev',
    linked_ids: ['sci-lore-001', 'sci-lore-002']
  } as TaskEntity,
];
