
import { 
  AppEntity, 
  EntityStatus, 
  EntityType, 
  LoreEntity, 
  AssetEntity, 
  AIEntity, 
  CodeEntity, 
  TaskEntity,
  Project
} from './types';

// Helper to generate ISO dates
const now = new Date().toISOString();
const past = (days: number) => new Date(Date.now() - days * 86400000).toISOString();

export const PROJECTS: Project[] = [
  {
    id: 'p1',
    name: 'Chronos: The Gilded Age',
    name_zh: '时空之轮：镀金时代',
    description: 'Steampunk Time-Travel RPG',
    themeColor: 'amber'
  },
  {
    id: 'p2',
    name: 'Ares Mystica',
    name_zh: '战神秘史 (火星玄幻)',
    description: 'Ancient Martian Fantasy & Magic',
    themeColor: 'red'
  },
  {
    id: 'p3',
    name: 'Red Horizon',
    name_zh: '红色地平线 (火星科幻)',
    description: 'Hard Sci-Fi Colonization Sim',
    themeColor: 'blue'
  }
];

export const MOCK_DATA: AppEntity[] = [
  // ==============================================
  // PROJECT 1: CHRONOS (Time Travel)
  // ==============================================
  {
    id: 'lore-001',
    projectId: 'p1',
    title: 'Emperor Valerius "The Clockmaker"',
    title_zh: '瓦勒留斯大帝 “钟表匠”',
    description: 'The antagonist of Act I. Obsessed with reversing the fall of his empire using forbidden chronomancy.',
    description_zh: '第一幕的反派。痴迷于利用禁忌的时间法术逆转帝国的衰落。',
    type: EntityType.LORE,
    status: EntityStatus.APPROVED,
    tags: ['character', 'antagonist', 'boss'],
    category: 'Character',
    content: 'Valerius was born during the Great Eclipse...',
    content_zh: '瓦勒留斯出生于大日食期间，天生对时间流动异常敏感...',
    created_at: past(30),
    updated_at: past(2),
    author_id: 'writer_sarah',
    linked_ids: ['asset-001', 'lore-002', 'ai-002'] 
  } as LoreEntity,
  {
    id: 'lore-002',
    projectId: 'p1',
    title: 'The Gilded Chrono-Dial',
    title_zh: '镀金时空刻度盘',
    description: 'An ancient artifact capable of localized time reversal. Requires significant energy sources.',
    description_zh: '一件能够局部逆转时间的古老神器。需要巨大的能量源才能启动。',
    type: EntityType.LORE,
    status: EntityStatus.APPROVED,
    tags: ['item', 'key-item', 'magic'],
    category: 'Artifact',
    content: 'Forged in the fires of the Temporal Spire...',
    content_zh: '这件神器是在时间尖塔的永恒之火中锻造而成的...',
    created_at: past(28),
    updated_at: past(10),
    author_id: 'writer_sarah',
    linked_ids: ['lore-001', 'asset-002', 'code-001']
  } as LoreEntity,
  {
    id: 'lore-003',
    projectId: 'p1',
    title: 'The Temporal Spire',
    title_zh: '时间尖塔',
    description: 'The final dungeon of the game. A tower existing outside of linear time.',
    description_zh: '游戏的最终地下城。一座存在于线性时间之外的高塔。',
    type: EntityType.LORE,
    status: EntityStatus.DRAFT,
    tags: ['location', 'level', 'endgame'],
    category: 'Location',
    content: 'Architecture shifts between Victorian and Cybernetic styles...',
    content_zh: '塔内的建筑风格在维多利亚哥特式和赛博朋克风格之间不断变换...',
    created_at: past(15),
    updated_at: past(1),
    author_id: 'level_designer_mike',
    linked_ids: ['ai-001', 'task-002']
  } as LoreEntity,
  {
    id: 'asset-001',
    projectId: 'p1',
    title: 'Valerius_Base_Mesh_v4.fbx',
    title_zh: '瓦勒留斯_基础模型_v4.fbx',
    description: 'High poly sculpt of Emperor Valerius. Needs retopology.',
    description_zh: '瓦勒留斯大帝的高模雕刻。需要进行拓扑优化。',
    type: EntityType.ASSET,
    status: EntityStatus.REVIEW,
    tags: ['3d', 'character', 'high-poly'],
    fileType: 'Model',
    fileUrl: 'https://example.com/assets/valerius.fbx',
    fileSize: '450MB',
    version: 4,
    created_at: past(10),
    updated_at: past(1),
    author_id: 'artist_jen',
    linked_ids: ['lore-001', 'task-001']
  } as AssetEntity,
  {
    id: 'asset-002',
    projectId: 'p1',
    title: 'Chrono_Dial_Texture_Atlas.png',
    title_zh: '刻度盘_纹理贴图集.png',
    description: 'PBR textures for the Chrono-Dial artifact.',
    description_zh: '时空刻度盘神器的 PBR 材质贴图。',
    type: EntityType.ASSET,
    status: EntityStatus.APPROVED,
    tags: ['texture', 'pbr', 'prop'],
    fileType: 'Texture',
    fileUrl: 'https://picsum.photos/200/200',
    fileSize: '24MB',
    version: 2,
    created_at: past(8),
    updated_at: past(5),
    author_id: 'artist_jen',
    linked_ids: ['lore-002']
  } as AssetEntity,
  {
    id: 'ai-001',
    projectId: 'p1',
    title: 'Spire Architecture Generator',
    title_zh: '尖塔建筑风格生成器',
    description: 'Prompt engineering setup to generate shifting architectural concepts for the Temporal Spire.',
    description_zh: '用于生成时间尖塔变幻莫测的建筑概念图的提示词工程设置。',
    type: EntityType.AI,
    status: EntityStatus.APPROVED,
    tags: ['gen-ai', 'concept-art', 'environment'],
    modelName: 'Gemini-3-Pro-Image-Preview',
    promptTemplate: 'A surreal tower combining Victorian gothic details with futuristic neon circuitry, fog atmosphere, perspective from below looking up...',
    description_zh_prompt: '一座超现实的高塔，结合了维多利亚哥特式细节和未来主义霓虹电路...', 
    parameters: { temperature: 0.8, seed: 42 },
    created_at: past(14),
    updated_at: past(12),
    author_id: 'tech_art_lead',
    linked_ids: ['lore-003', 'asset-003']
  } as AIEntity,
  {
    id: 'ai-002',
    projectId: 'p1',
    title: 'NPC Dialogue: Arrogant Emperor',
    title_zh: 'NPC对话：傲慢的大帝',
    description: 'System instruction for generating dynamic taunts from Valerius during combat.',
    description_zh: '用于在战斗中生成瓦勒留斯动态嘲讽台词的系统指令。',
    type: EntityType.AI,
    status: EntityStatus.REVIEW,
    tags: ['nlp', 'dialogue', 'gameplay'],
    modelName: 'Gemini-2.5-Flash',
    promptTemplate: 'You are Emperor Valerius. You are arrogant, timeless, and see the player as a "fleeting second". Generate a combat taunt based on the player losing health.',
    parameters: { temperature: 1.1, topK: 40 },
    created_at: past(5),
    updated_at: now,
    author_id: 'narrative_designer',
    linked_ids: ['lore-001', 'code-002']
  } as AIEntity,
  {
    id: 'code-001',
    projectId: 'p1',
    title: 'TimeRewindManager.cs',
    title_zh: 'TimeRewindManager.cs (时间倒流管理)',
    description: 'Core logic for recording entity positions and rewinding them on trigger.',
    description_zh: '用于记录实体位置并在触发时倒流的核心逻辑代码。',
    type: EntityType.CODE,
    status: EntityStatus.APPROVED,
    tags: ['c#', 'unity', 'gameplay-mechanic'],
    language: 'C#',
    codeSnippet: `public class TimeRewindManager : MonoBehaviour { ... }`,
    created_at: past(40),
    updated_at: past(2),
    author_id: 'dev_alex',
    linked_ids: ['lore-002']
  } as CodeEntity,
  {
    id: 'code-002',
    projectId: 'p1',
    title: 'LLM_Runtime_Bridge.py',
    title_zh: 'LLM_Runtime_Bridge.py (大模型桥接)',
    description: 'Python service to proxy game state to the LLM for dynamic dialogue.',
    description_zh: '用于将游戏状态代理到 LLM 以生成动态对话的 Python 服务。',
    type: EntityType.CODE,
    status: EntityStatus.DRAFT,
    tags: ['python', 'backend', 'ai-integration'],
    language: 'Python',
    codeSnippet: `def get_boss_taunt(player_hp, boss_phase): ...`,
    created_at: past(4),
    updated_at: now,
    author_id: 'dev_alex',
    linked_ids: ['ai-002']
  } as CodeEntity,
  {
    id: 'task-001',
    projectId: 'p1',
    title: 'Retopologize Valerius Model',
    title_zh: '瓦勒留斯模型拓扑优化',
    description: 'The high poly sculpt is too heavy. Needs to be reduced to <50k tris for engine import.',
    description_zh: '高模雕刻面数过高。需要减少到 50k 三角面以下以便导入引擎。',
    type: EntityType.TASK,
    status: EntityStatus.REVIEW,
    tags: ['art', 'optimization'],
    priority: 'High',
    assignee: 'artist_jen',
    dueDate: new Date(Date.now() + 86400000 * 5).toISOString(),
    isMilestone: false,
    created_at: past(2),
    updated_at: past(1),
    author_id: 'prod_manager',
    linked_ids: ['asset-001']
  } as TaskEntity,
  {
    id: 'task-002',
    projectId: 'p1',
    title: 'Finalize Spire Level Blockout',
    title_zh: '完成尖塔关卡白盒',
    description: 'Need greybox geometry for the Temporal Spire based on the new concept art.',
    description_zh: '根据新的概念图，完成时间尖塔的白盒（Greybox）几何体搭建。',
    type: EntityType.TASK,
    status: EntityStatus.DRAFT,
    tags: ['level-design', 'blockout'],
    priority: 'Medium',
    assignee: 'level_designer_mike',
    dueDate: new Date(Date.now() + 86400000 * 10).toISOString(),
    isMilestone: true,
    created_at: past(5),
    updated_at: past(5),
    author_id: 'prod_manager',
    linked_ids: ['lore-003']
  } as TaskEntity,

  // ==============================================
  // PROJECT 2: ARES MYSTICA (Mars Fantasy)
  // ==============================================
  {
    id: 'mars-lore-001',
    projectId: 'p2',
    title: 'The Crimson High Priest',
    title_zh: '猩红大祭司',
    description: 'Leader of the Dust Walkers. Wields magic drawn from the iron oxide sands.',
    description_zh: '尘行者的领袖。能够从氧化铁沙中汲取魔力。',
    type: EntityType.LORE,
    status: EntityStatus.APPROVED,
    tags: ['character', 'mars', 'magic'],
    category: 'Character',
    content: 'The High Priest claims to hear the breathing of the planet...',
    content_zh: '大祭司声称能听到星球的呼吸声...',
    created_at: past(100),
    updated_at: past(10),
    author_id: 'writer_bob',
    linked_ids: ['mars-asset-001', 'mars-ai-001']
  } as LoreEntity,
  {
    id: 'mars-asset-001',
    projectId: 'p2',
    title: 'Obsidian_Staff.obj',
    title_zh: '黑曜石法杖.obj',
    description: 'Ceremonial staff for the High Priest. Needs glowing rune effects.',
    description_zh: '大祭司的仪式法杖。需要添加发光的符文特效。',
    type: EntityType.ASSET,
    status: EntityStatus.REVIEW,
    tags: ['3d', 'weapon', 'prop'],
    fileType: 'Model',
    fileUrl: 'https://example.com/assets/staff.obj',
    fileSize: '45MB',
    version: 1,
    created_at: past(20),
    updated_at: past(5),
    author_id: 'artist_ken',
    linked_ids: ['mars-lore-001']
  } as AssetEntity,
  {
    id: 'mars-ai-001',
    projectId: 'p2',
    title: 'Ancient Martian Runes Generator',
    title_zh: '古火星符文生成器',
    description: 'Generates mystical glowing symbols for texture overlays.',
    description_zh: '生成用于纹理叠加的神秘发光符号。',
    type: EntityType.AI,
    status: EntityStatus.APPROVED,
    tags: ['gen-ai', 'texture'],
    modelName: 'Gemini-2.5-Flash-Image',
    promptTemplate: 'Glowing jagged runes carved into red rock, alien language, mystical energy...',
    parameters: { temperature: 0.9, seed: 101 },
    created_at: past(15),
    updated_at: past(2),
    author_id: 'tech_art_lead',
    linked_ids: ['mars-asset-001']
  } as AIEntity,

  // ==============================================
  // PROJECT 3: RED HORIZON (Mars Sci-Fi)
  // ==============================================
  {
    id: 'sci-lore-001',
    projectId: 'p3',
    title: 'Colony Alpha',
    title_zh: '阿尔法殖民地',
    description: 'The first successful permanent settlement in the Valles Marineris.',
    description_zh: '水手号峡谷中第一个成功的永久定居点。',
    type: EntityType.LORE,
    status: EntityStatus.APPROVED,
    tags: ['location', 'base', 'sci-fi'],
    category: 'Location',
    content: 'Established in 2045, Alpha serves as the hub for terraforming...',
    content_zh: '建立于2045年，阿尔法是地球化改造的中心枢纽...',
    created_at: past(200),
    updated_at: past(20),
    author_id: 'writer_dave',
    linked_ids: ['sci-asset-001', 'sci-task-001']
  } as LoreEntity,
  {
    id: 'sci-asset-001',
    projectId: 'p3',
    title: 'Terraforming_Unit_v2.fbx',
    title_zh: '大气改造装置_v2.fbx',
    description: 'Industrial heavy machinery asset for the colony exterior.',
    description_zh: '用于殖民地外部的工业重型机械资产。',
    type: EntityType.ASSET,
    status: EntityStatus.APPROVED,
    tags: ['3d', 'hard-surface', 'building'],
    fileType: 'Model',
    fileUrl: 'https://example.com/assets/terraformer.fbx',
    fileSize: '120MB',
    version: 2,
    created_at: past(30),
    updated_at: past(10),
    author_id: 'artist_sarah',
    linked_ids: ['sci-lore-001']
  } as AssetEntity,
  {
    id: 'sci-task-001',
    projectId: 'p3',
    title: 'Fix Oxygen Leak Script',
    title_zh: '修复氧气泄漏脚本',
    description: 'Bug in the life support system logic causing false alarms.',
    description_zh: '生命维持系统逻辑中的 Bug 导致误报。',
    type: EntityType.TASK,
    status: EntityStatus.REVIEW,
    tags: ['bug', 'gameplay'],
    priority: 'Critical',
    assignee: 'dev_mike',
    dueDate: now,
    isMilestone: false,
    created_at: past(2),
    updated_at: now,
    author_id: 'lead_dev',
    linked_ids: ['sci-lore-001']
  } as TaskEntity,
];
